#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Executar lint-staged (linting e formatação)
npm run pre-commit

# Executar todos os testes - falha o commit se os testes falharem
yarn test:pre-commit
